name: check

on:
  push:
    branches: [develop, main, release/**]
  pull_request:
    branches: [develop, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install stable --component rustfmt --component clippy
          rustup default stable

      - name: rust cache
        uses: Swatinem/rust-cache@v2

      - name: fmt
        run: cargo fmt --check

      - name: check
        run: cargo check --locked

      - name: clippy
        run: cargo clippy --locked -- -D warnings
